# This file was generated by `yo terraform-module` using template v1.0.0, hash: 38783d0f9dc0c097954b121e09ddd96a)

# Create a new instance of the latest Ubuntu 14.04 on an
# t2.micro node with an AWS Tag naming it "HelloWorld"
provider "aws" {
  region = "us-west-2"
}

data "aws_ami" "centos" {
  most_recent = true

  filter {
    name   = "name"
    values = ["centos*1805_01*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

#  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "worker" {
  ami           = "${data.aws_ami.centos.id}"
  instance_type = "${var.instance_type}"
  key_name      = "${var.key_name}"

  user_data = "${file("./userdata.sh")}"
}

resource "null_resource" "build_dcos" {
  # Changes to any instance of the cluster requires re-provisioning
  triggers = {
    cluster_instance_ids = "${aws_instance.worker.id}"
    contents_md5sha = "${md5(file("./build_script.sh"))}"
  }

  # Bootstrap script can run on any instance of the cluster
  # So we just choose the first in this case
  connection {
    host        = "${aws_instance.worker.public_ip}"
    user        = "${var.user}"
    agent       = "false"
    private_key = "${file("${var.private_key_path}")}"
  }

  provisioner "file" {
    source      = "./build_script.sh"
    destination = "build_script.sh"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x build_script.sh",
      "./build_script.sh",
    ]
  }
}
