# This file was generated by `yo terraform-module` using template v1.0.0, hash: 9a83b2f78e96fa3fbb6350e6282b8b3b)

variable "key_name" {
  default = "default"
}

variable "user" {
  default = "centos"
}

variable "private_key_path" {
  default = "~/.ssh/key.pem"
}

variable "instance_type" {
  default = "m5.xlarge"
}

variable "owner" {
  description = "Paired with Cloud Cluster Cleaner will notify on expiration via slack. Default is whoami. Can be overwritten by setting the value here"
  default = "mbernadin"
}

variable "expiration" {
  description = "Paired with Cloud Cluster Cleaner will notify on expiration via slack"
  default = "4h"
}
